# Generated by Django 4.1.5 on 2023-01-25 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_categories_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 4, 43, 29, 673607, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
