# Generated by Django 4.1.5 on 2023-01-25 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 5, 7, 4, 809552, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
