# Generated by Django 4.1.5 on 2023-01-26 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 1, 20, 9, 447671, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
