# Generated by Django 4.1.5 on 2023-01-30 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 2, 28, 3, 617997, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
